language: ruby
rvm: 1.9.2
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "bundle exec rake db:migrate"
notifications:
  email:
    - sebastian.meyer@student.hpi.uni-potsdam.de
    - jharzmann@gmail.com
    - flwe11@student.bth.se
    - topf11@student.bth.se

