require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SprintsController do

  # This should return the minimal set of attributes required to create a valid
  # Sprint. As you add validations to Sprint, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    Factory.attributes_for(:sprint)
  end

  describe "GET index" do
    it "assigns all sprints as @sprints" do
      sprint = Sprint.create! valid_attributes
      get :index
      assigns(:sprints).should eq([sprint])
    end
  end

  describe "GET show" do
    it "assigns the requested sprint as @sprint" do
      sprint = Sprint.create! valid_attributes
      get :show, :id => sprint.id
      assigns(:sprint).should eq(sprint)
    end
  end

  describe "GET new" do
    it "assigns a new sprint as @sprint" do
      get :new
      assigns(:sprint).should be_a_new(Sprint)
    end
  end

  describe "GET edit" do
    it "assigns the requested sprint as @sprint" do
      sprint = Sprint.create! valid_attributes
      get :edit, :id => sprint.id
      assigns(:sprint).should eq(sprint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sprint" do
        expect {
          post :create, :sprint => valid_attributes
        }.to change(Sprint, :count).by(1)
      end

      it "assigns a newly created sprint as @sprint" do
        post :create, :sprint => valid_attributes
        assigns(:sprint).should be_a(Sprint)
        assigns(:sprint).should be_persisted
      end

      it "redirects to the created sprint" do
        post :create, :sprint => valid_attributes
        response.should redirect_to(Sprint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sprint as @sprint" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sprint.any_instance.stub(:save).and_return(false)
        post :create, :sprint => {}
        assigns(:sprint).should be_a_new(Sprint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sprint.any_instance.stub(:save).and_return(false)
        post :create, :sprint => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do

      it "updates the requested sprint" do
        sprint = Sprint.create! valid_attributes
        # Assuming there are no other sprints in the database, this
        # specifies that the Sprint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sprint.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sprint.id, :sprint => {'these' => 'params'}
      end

      it "assigns the requested sprint as @sprint" do
        sprint = Sprint.create! valid_attributes
        put :update, :id => sprint.id, :sprint => valid_attributes
        assigns(:sprint).should eq(sprint)
      end

      it "redirects to the sprint" do
        sprint = Sprint.create! valid_attributes
        put :update, :id => sprint.id, :sprint => valid_attributes
        response.should redirect_to(sprint)
      end
    end

    describe "with invalid params" do
      it "assigns the sprint as @sprint" do
        sprint = Sprint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sprint.any_instance.stub(:save).and_return(false)
        put :update, :id => sprint.id, :sprint => {}
        assigns(:sprint).should eq(sprint)
      end

      it "re-renders the 'edit' template" do
        sprint = Sprint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sprint.any_instance.stub(:save).and_return(false)
        put :update, :id => sprint.id, :sprint => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sprint" do
      sprint = Sprint.create! valid_attributes
      expect {
        delete :destroy, :id => sprint.id
      }.to change(Sprint, :count).by(-1)
    end

    it "redirects to the sprints list" do
      sprint = Sprint.create! valid_attributes
      delete :destroy, :id => sprint.id
      response.should redirect_to(sprints_url)
    end
  end

end

