require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserStoriesController do

  before :each do
    @user_story = Factory(:user_story)
  end

  # This should return the minimal set of attributes required to create a valid
  # UserStory. As you add validations to UserStory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {name: "My User Story"}
  end

  describe "GET index" do
    it "assigns all user_stories as @user_stories" do
      get :index
      assigns(:user_stories).should eq([@user_story])
    end
  end

  describe "GET show" do
    it "assigns the requested @user_story as @@user_story" do
      get :show, :id => @user_story.id
      assigns(:user_story).should eq(@user_story)
    end
  end

  describe "GET new" do
    it "assigns a new @user_story as @@user_story" do
      get :new
      assigns(:user_story).should be_a_new(UserStory)
    end
  end

  describe "GET edit" do
    it "assigns the requested @user_story as @@user_story" do
      get :edit, :id => @user_story.id
      assigns(:user_story).should eq(@user_story)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserStory" do
        expect {
          post :create, :user_story => valid_attributes
        }.to change(UserStory, :count).by(1)
      end

      it "assigns a newly created @user_story as @@user_story" do
        post :create, :user_story => valid_attributes
        assigns(:user_story).should be_a(UserStory)
        assigns(:user_story).should be_persisted
      end

      it "redirects to the created @user_story" do
        post :create, :user_story => valid_attributes
        response.should redirect_to(UserStory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved @user_story as @@user_story" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserStory.any_instance.stub(:save).and_return(false)
        post :create, :user_story => {}
        assigns(:user_story).should be_a_new(UserStory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserStory.any_instance.stub(:save).and_return(false)
        post :create, :user_story => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested @user_story" do
        # Assuming there are no other user_stories in the database, this
        # specifies that the UserStory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserStory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => @user_story.id, :user_story => {'these' => 'params'}
      end

      it "assigns the requested @user_story as @@user_story" do
        put :update, :id => @user_story.id, :user_story => valid_attributes
        assigns(:user_story).should eq(@user_story)
      end

      it "redirects to the @user_story" do
        put :update, :id => @user_story.id, :user_story => valid_attributes
        response.should redirect_to(@user_story)
      end
    end

    describe "with invalid params" do
      it "assigns the @user_story as @@user_story" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserStory.any_instance.stub(:save).and_return(false)
        put :update, :id => @user_story.id, :user_story => {}
        assigns(:user_story).should eq(@user_story)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserStory.any_instance.stub(:save).and_return(false)
        put :update, :id => @user_story.id, :user_story => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested @user_story" do
      expect {
        delete :destroy, :id => @user_story.id
      }.to change(UserStory, :count).by(-1)
    end

    it "redirects to the user_stories list" do
      delete :destroy, :id => @user_story.id
      response.should redirect_to(user_stories_url)
    end
  end

end

